[tool.poetry]
name = "packet-sniffer"
version = "0.1.0"
description = ""
authors = ["<Your name>"]
[tool.poetry.dependencies]
python = "^3.7"
scapy = "^2.4"
netifaces = "^0.10.9"
PyInquirer = "^1.0"
[tool.poetry.dev-dependencies]
bpython = "^0.19.0"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"